import type { CurriculumPath } from "./types";

export const paths: CurriculumPath[] = [
  {
    id: "general",
    course: "General English",
    emoji: "📘",
    color: "emerald",
    imageUrl: "/images/path-general.svg",
    price: 0,
    currency: "IDR",
    units: [
      {
        id: "u1",
        title: "Unit 1: Basics",
        sequence: 1,
        brandColor: "emerald",
        badge: { status: "in_progress", title: "Unit Badge" },
        nodes: [
          {
            id: "n1",
            title: "Greetings",
            description: "Basic hello/bye phrases",
            status: "completed",
            xpReward: 10,
            durationSec: 80,
          },
          {
            id: "n2",
            title: "Alphabet",
            description: "Pronouncing letters A–Z",
            status: "in_progress",
            xpReward: 10,
            durationSec: 90,
          },
          {
            id: "ad-u1-1",
            title: "ADS",
            status: "in_progress",
            xpReward: 0,
            durationSec: 30,
            kind: "ad",
            ad: {
              id: "ad-yt-001",
              provider: "YouTube",
              mediaUrl: "https://youtu.be/dQw4w9WgXcQ",
            },
          },
          {
            id: "n3",
            title: "Numbers",
            description: "Counting from 1 to 100",
            status: "locked",
            xpReward: 10,
            durationSec: 85,
          },
        ],
      },
      {
        id: "u2",
        title: "Unit 2: Daily Life",
        sequence: 2,
        brandColor: "sky",
        badge: { status: "locked", title: "Unit Badge" },
        nodes: [
          {
            id: "n4",
            title: "Routine",
            description: "Describe daily activities",
            status: "locked",
            xpReward: 10,
            durationSec: 95,
          },
          {
            id: "n5",
            title: "Shopping",
            description: "Buying items and asking prices",
            status: "locked",
            xpReward: 10,
            durationSec: 88,
          },
          {
            id: "n6",
            title: "Food",
            description: "Common food vocabulary",
            status: "locked",
            xpReward: 10,
            durationSec: 92,
          },
        ],
      },
      {
        id: "u3",
        title: "Unit 3: Travel",
        sequence: 3,
        brandColor: "violet",
        badge: { status: "locked", title: "Unit Badge" },
        nodes: [
          {
            id: "n7",
            title: "Airport",
            description: "Check-in and boarding",
            status: "locked",
            xpReward: 10,
            durationSec: 100,
          },
          {
            id: "n8",
            title: "Hotel",
            description: "Reservations and requests",
            status: "locked",
            xpReward: 10,
            durationSec: 97,
          },
          {
            id: "n9",
            title: "Directions",
            description: "Asking and giving directions",
            status: "locked",
            xpReward: 10,
            durationSec: 104,
          },
        ],
      },
      {
        id: "u4",
        title: "Unit 4: Vocabulary & Reading",
        sequence: 4,
        brandColor: "sky",
        badge: { status: "in_progress", title: "Unit Badge" },
        nodes: [
          {
            id: "vocab-101",
            title: "Vocabulary Drill",
            description: "Mark known vs learn",
            status: "in_progress",
            xpReward: 10,
            durationSec: 60,
          },
          {
            id: "reading-101",
            title: "Reading Practice",
            description: "Paragraphs + quizzes",
            status: "in_progress",
            xpReward: 10,
            durationSec: 90,
          },
        ],
      },
    ],
  },
  {
    id: "business",
    course: "Business English",
    emoji: "💼",
    color: "sky",
    imageUrl: "/images/path-business.svg",
    price: 150000,
    originalPrice: 299000,
    currency: "IDR",
    description: "Master professional communication and advance your career.",
    learningPoints: [
      "Write effective emails",
      "Lead meetings confidently",
      "Negotiate like a pro",
      "Business vocabulary mastery",
    ],
    estimatedTime: "6 weeks",
    studentsCount: 3215,
    difficulty: "Intermediate",
    certificate: true,
    language: "English",
    subtitles: ["English", "Indonesian"],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    badgeImg: "/images/badge-business.svg",
    certificateImg: "/images/certificate-business.svg",
    units: [
      {
        id: "bu1",
        title: "Unit 1: Emails",
        sequence: 1,
        brandColor: "indigo",
        badge: { status: "in_progress", title: "Unit Badge" },
        nodes: [
          {
            id: "bn1",
            title: "Greetings",
            description: "Formal vs casual greetings",
            status: "completed",
            xpReward: 10,
            durationSec: 80,
            finish: {
              praise: "Awesome!",
              animation: {
                kind: "lottie",
                src: "/medals.json",
                fallbackSrc: "/window.svg",
              },
            },
          },
          {
            id: "bn2",
            title: "Subject Lines",
            description: "Clear and effective subjects",
            status: "in_progress",
            xpReward: 10,
            durationSec: 90,
          },
          {
            id: "ad-bu1-1",
            title: "ADS",
            status: "in_progress",
            xpReward: 0,
            durationSec: 30,
            kind: "ad",
            ad: { id: "ad-yt-002", provider: "YouTube" },
          },
          {
            id: "bn3",
            title: "Closings",
            description: "Professional email endings",
            status: "locked",
            xpReward: 10,
            durationSec: 85,
          },
        ],
      },
      {
        id: "bu2",
        title: "Unit 2: Meetings",
        sequence: 2,
        brandColor: "amber",
        badge: { status: "locked", title: "Unit Badge" },
        nodes: [
          {
            id: "bn4",
            title: "Agenda",
            description: "Setting meeting goals",
            status: "locked",
            xpReward: 10,
            durationSec: 95,
          },
          {
            id: "bn5",
            title: "Decision",
            description: "Recording decisions",
            status: "locked",
            xpReward: 10,
            durationSec: 88,
          },
          {
            id: "bn6",
            title: "Follow-up",
            description: "Next steps and action items",
            status: "locked",
            xpReward: 10,
            durationSec: 92,
          },
        ],
      },
    ],
  },
  {
    id: "kids",
    course: "English for Kids",
    emoji: "🧸",
    color: "amber",
    imageUrl: "/images/path-kids.svg",
    price: 99000,
    originalPrice: 199000,
    currency: "IDR",
    description: "Fun and engaging lessons designed specifically for children.",
    learningPoints: [
      "Basic vocabulary",
      "Fun songs and games",
      "Simple sentence structure",
      "Interactive storytelling",
    ],
    estimatedTime: "4 weeks",
    studentsCount: 5430,
    difficulty: "Beginner",
    certificate: true,
    language: "English",
    subtitles: ["English", "Indonesian"],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    units: [
      {
        id: "k1",
        title: "Unit 1: Fun Basics",
        sequence: 1,
        brandColor: "rose",
        badge: { status: "locked", title: "Unit Badge" },
        nodes: [
          {
            id: "kn1",
            title: "Colors",
            description: "Learn basic colors",
            status: "locked",
            xpReward: 10,
            durationSec: 60,
          },
          {
            id: "ad-k1-1",
            title: "ADS",
            status: "in_progress",
            xpReward: 0,
            durationSec: 20,
            kind: "ad",
            ad: { id: "ad-yt-003", provider: "YouTube" },
          },
          {
            id: "kn2",
            title: "Animals",
            description: "Common animals",
            status: "locked",
            xpReward: 10,
            durationSec: 70,
          },
          {
            id: "kn3",
            title: "Fruits",
            description: "Favorite fruits",
            status: "locked",
            xpReward: 10,
            durationSec: 65,
          },
        ],
      },
    ],
  },
  {
    id: "travel2",
    course: "Travel English",
    emoji: "✈️",
    color: "indigo",
    imageUrl: "/images/path-travel.svg",
    price: 120000,
    originalPrice: 249000,
    currency: "IDR",
    description: "Essential phrases and confidence for your next adventure.",
    learningPoints: [
      "Airport and hotel check-in",
      "Asking for directions",
      "Ordering food",
      "Emergency situations",
    ],
    estimatedTime: "3 weeks",
    studentsCount: 2100,
    difficulty: "Beginner",
    certificate: true,
    language: "English",
    subtitles: ["English", "Indonesian"],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    units: [
      {
        id: "t1",
        title: "Unit 1: Basics",
        sequence: 1,
        brandColor: "sky",
        badge: { status: "in_progress", title: "Unit Badge" },
        nodes: [
          {
            id: "tn1",
            title: "Tickets",
            description: "Buying tickets",
            status: "in_progress",
            xpReward: 10,
            durationSec: 80,
          },
          {
            id: "ad-t1-1",
            title: "ADS",
            status: "in_progress",
            xpReward: 0,
            durationSec: 25,
            kind: "ad",
            ad: { id: "ad-yt-004", provider: "YouTube" },
          },
          {
            id: "tn2",
            title: "Boarding",
            description: "Boarding steps",
            status: "locked",
            xpReward: 10,
            durationSec: 90,
          },
          {
            id: "tn3",
            title: "Customs",
            description: "Customs questions",
            status: "locked",
            xpReward: 10,
            durationSec: 85,
          },
        ],
      },
    ],
  },
];
